BookHiveDB.Web/Controllers/Mvc/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BookHiveDB.Domain.Dtos.Mvc;
using BookHiveDB.Domain.Models;
using BookHiveDB.Service.Interface;
using ExcelDataReader;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookHiveDB.Web.Controllers.Mvc
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorService _authorService;

        public AuthorsController(IAuthorService authorService)
        {
            _authorService = authorService;
        }

        // GET: Authors
        public IActionResult Index()
        {
            return View(_authorService.findAll());
        }

        // GET: Authors/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var author = _authorService.findById(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("name,surname,age,biography,Id")] Author author)
        {
            if (!ModelState.IsValid) return View(author);
            author.Id = Guid.NewGuid();
            _authorService.Insert(author);
            return RedirectToAction(nameof(Index));
        }


        public  IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.findById(id.Value);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("name,surname,age,biography,Id")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid) return View(author);
            
            try
            {
                _authorService.Update(author);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuthorExists(author.Id))
                {
                    return NotFound();
                }

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

     
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.findById(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _authorService.deleteById(id);
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(Guid id)
        {
            return _authorService.findById(id) != null;
        }


        public ActionResult ImportAuthorsView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImportAuthors(IFormFile file)
        {
            string pathToUpload = $"{Directory.GetCurrentDirectory()}\\files\\{file.FileName}";

            using (FileStream fileStream = System.IO.File.Create(pathToUpload))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }

            List<UserExcelDto> authors = getAllAuthorsFromFile(file.FileName);

            foreach (var author in authors)
            {
                _authorService.add(author.name, author.surname, author.age, author.biography);
            }
            return RedirectToAction("Index"); 
        }

        private List<UserExcelDto> getAllAuthorsFromFile(string fileName)
        {
            List<UserExcelDto> authors = new List<UserExcelDto>();
            string filePath = $"{Directory.GetCurrentDirectory()}\\files\\{fileName}";
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            using (var stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    while (reader.Read())
                    {
                        authors.Add(new UserExcelDto
                        {
                            name = reader.GetValue(0).ToString(),
                            surname = reader.GetValue(1).ToString(),
                            age = Convert.ToInt32(reader.GetValue(2)),
                            biography = reader.GetValue(3).ToString()
                        });
                    }
                }
            }
            return authors;
        }
    }
}

BookHiveDB.Web/Controllers/Mvc/OrderController.cs
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using BookHiveDB.Domain;
using BookHiveDB.Domain.Identity;
using BookHiveDB.Service.Interface;
using GemBox.Document;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookHiveDB.Web.Controllers.Mvc
{
    public class OrderController : Controller
    {

        private readonly IOrderService _orderService;
        private readonly UserManager<BookHiveApplicationUser> _userManager;


        public OrderController(IOrderService orderService, UserManager<BookHiveApplicationUser> userManager)
        {
            _orderService = orderService;
            _userManager = userManager;
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");
        }

        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userManager.FindByIdAsync(userId).Result;
            var orders = _orderService.getAllOrders();

            if (_userManager.IsInRoleAsync(user, "Administrator").Result)
            {
                return View(orders);
            }
            // if not administrator show only his orders
            foreach (var order in orders.ToList().Where(order => !order.UserId.Equals(userId)))
            {
                orders.Remove(order);
            }
            return View(orders);
        }

        public IActionResult Details(Guid id)
        {
            var baseEntity = new BaseEntity { Id = id };
            var order = _orderService.getOrderDetails(baseEntity);
            return View(order);
        }

        public IActionResult CreateInvoice(Guid id)
        {
            var baseEntity = new BaseEntity { Id = id };
            var order = _orderService.getOrderDetails(baseEntity);


            var templatePath = Path.Combine(Directory.GetCurrentDirectory(), "Invoice.docx");

            var document = DocumentModel.Load(templatePath);

            document.Content.Replace("{{OrderNumber}}", order.Id.ToString());
            document.Content.Replace("{{UserName}}", order.User.UserName);


            var sb = new StringBuilder();
            var totalPrice = 0.0;
            foreach(var bookInOrder in order.BooksInOrders)
            {
                sb.AppendLine(bookInOrder.Book.Name + " with quantity of: " + bookInOrder.Quantity + " and price of: " + bookInOrder.Book.Price + " dollars");
                totalPrice += bookInOrder.Quantity * bookInOrder.Book.Price;
            }

            document.Content.Replace("{{BookList}}", sb.ToString());
            document.Content.Replace("{{TotalPrice}}", totalPrice + "$");

            var stream = new MemoryStream();
            document.Save(stream, new PdfSaveOptions());
            return File(stream.ToArray(), new PdfSaveOptions().ContentType, "ExportInvoice.pdf");
        }
    }
}

BookHiveDB.Web/Controllers/Mvc/UserBooksController.cs
using System;
using System.Security.Claims;
using BookHiveDB.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace BookHiveDB.Web.Controllers.Mvc
{
    public class UserBooksController : Controller
    {
        private readonly IUserService _userService;
        private readonly IUserBookService _userBookService;
        private readonly IBookService _bookService;


        public UserBooksController(IUserBookService userBookService, IUserService userService, IBookService bookService)
        {
            _userBookService = userBookService;
            _userService = userService;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userService.findById(userId);
            return View(_userBookService.FindByUser(user));
        }

        public IActionResult Create(Guid id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _userBookService.addBookToMyBooks(userId, id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid bookId, int lastPage)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _userBookService.editLastPageReadForBook(userId, bookId, lastPage);

            var user = _userService.findById(userId);
            var book = _bookService.findById(bookId);
            var userbook = _userBookService.FindByUserAndBook(user, book);

            userbook.lastPageRead = lastPage > book.TotalPages ? book.TotalPages : lastPage;
            _userBookService.Update(userbook);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            var obj = _userBookService.Get(id);
            return View(obj);
        }

        public IActionResult DeleteConfirmed(Guid id)
        {
            _userBookService.RemoveFromMyBooks(id);
            return RedirectToAction("Index");
        }
    }
}

BookHiveDB.Web/Controllers/Mvc/UserController.cs
using System;
using System.Threading.Tasks;
using BookHiveDB.Domain.Dtos.Mvc;
using BookHiveDB.Domain.Identity;
using BookHiveDB.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookHiveDB.Web.Controllers.Mvc
{
    public class UserController : Controller
    {

        private readonly IBookInWishListService _bookInWishListService;
        private readonly IBookClubService _bookClubService;
        private readonly UserManager<BookHiveApplicationUser> _userManager;
        private readonly IBookService _bookService;

        public UserController(IBookInWishListService bookInWishListService, IBookClubService bookClubService, UserManager<BookHiveApplicationUser> userManager, IBookService bookService)
        {
            _bookInWishListService = bookInWishListService;
            _bookClubService = bookClubService;
            _userManager = userManager;
            _bookService = bookService;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetMyBookClubs()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var myBookClubs = _bookClubService.findByMember(user.Id);
            var obj = new BookClubsLoggedInUser(myBookClubs, user);
            return View(obj);
        }

        public IActionResult LeaveBookClubPage(Guid bookClubId)
        {
            var obj = _bookClubService.findById(bookClubId);
            return View(obj);
            
        }
        public async Task<IActionResult> RemoveBookClubFromMyBookClubsAsync(Guid bookClubId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            _bookClubService.removeUserFromBookclub(bookClubId, user.Id);
            return RedirectToAction(nameof(GetMyBookClubs));
        }

        public async Task<IActionResult> AddBookToMyWishList(Guid bookId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            _bookInWishListService.addBookToMyWishlist(user.Id, bookId);
            return RedirectToAction(nameof(GetMyWishList));
        }
        public IActionResult RemoveBookPage(Guid bookId)
        {
            var obj = _bookService.findById(bookId);
            return View(obj);
        }

        public async Task<IActionResult> RemoveBookFromMyWishList(Guid bookId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            _bookInWishListService.removeBookFromMyWishlist(user.Id, bookId);
            return RedirectToAction(nameof(GetMyWishList));
        }

        public async Task<IActionResult> GetMyWishList()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var myWishList = _bookInWishListService.getAllBookInWishlistForUser(user.Id);
            return View(myWishList);
        }

    }
}

BookHiveDB.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - BookHiveDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="/style.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka&display=swap" rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>

    <style>
        @@import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
        body {
            font-family: 'Poppins', sans-serif;
            background: #fafafa;
        }

        p {
            font-family: 'Poppins', sans-serif;
            font-size: 1em;
            line-height: 1.7em;
        }

        #naslov {
            padding-top: 15px;
            font-family: 'Fredoka', sans-serif;
        }

        #navbarSupportedContent ul li a:hover {
            color: #FC766A;
        }

        #myProfile {
            color: #008C76;
            font-size: 20px;
        }

        #topbar {
            margin-top: -20px;
            margin-left: -20px;
            margin-right: -20px;
        }

        #logout {
            position: absolute;
            padding-left: 10px;
            padding-bottom: 7px;
            bottom: 0;
            font-size: 17px;
        }

        #sidebar a:hover {
            color: #FC766A;
        }

        a,
        a:hover,
        a:focus {
            color: inherit;
            text-decoration: none;
            transition: all 0.3s;
        }

        .navbar {
            padding: 20px 10px;
            background: #fff;
            border: none;
            border-radius: 0;
            margin-bottom: 40px;
            box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
        }

        .navbar-btn {
            box-shadow: none;
            outline: none !important;
            border: none;
        }

        .line {
            width: 100%;
            height: 1px;
            border-bottom: 1px dashed #ddd;
            margin: 40px 0;
        }

        /* ---------------------------------------------------
            SIDEBAR STYLE
        ----------------------------------------------------- */

        .wrapper {
            display: flex;
            width: 100%;
            align-items: stretch;
        }

        #sidebar {
            min-width: 230px;
            max-width: 230px;
            background-color: #008C76;
            color: #fff;
            transition: all 0.3s;
        }

        #sidebarCollapse {
            background-color: #008C76;
        }

        #sidebar.active {
            margin-left: -230px;
        }

        #sidebar .sidebar-header {
            padding-top: 15px;
            padding-bottom: 15px;
            padding-left: 10px;
            background-color: #008C76;
        }

        body {
            background-color: #9ED9CC;
        }

        #sidebar ul p {
            color: #fff;
            padding: 10px;
        }

        #sidebar ul li a {
            padding: 10px;
            font-size: 1.1em;
            display: block;
        }

        #sidebar ul li a:hover {
            color: #008C76;
            background: #fff;
        }

        #sidebar ul li.active>a,
        a[aria-expanded="true"] {
            color: #008C76;
            background: #fff;
        }

        a[data-toggle="collapse"] {
            position: relative;
        }

        .dropdown-toggle::after {
            display: block;
            position: absolute;
            top: 50%;
            right: 20px;
            transform: translateY(-50%);
        }

        ul ul a {
            font-size: 0.9em !important;
            padding-left: 30px !important;
            background: #6d7fcc;
        }

        ul.CTAs {
            padding: 20px;
        }

        ul.CTAs a {
            text-align: center;
            font-size: 0.9em !important;
            display: block;
            border-radius: 5px;
            margin-bottom: 5px;
        }

        a.download {
            background: #fff;
            color: #7386D5;
        }

        a.article,
        a.article:hover {
            background: #6d7fcc !important;
            color: #fff !important;
        }

        /* ---------------------------------------------------
            CONTENT STYLE
        ----------------------------------------------------- */

        #content {
            width: 100%;
            padding: 20px;
            min-height: 100vh;
            transition: all 0.3s;
        }

        /* ---------------------------------------------------
            MEDIAQUERIES
        ----------------------------------------------------- */

        @@media (max-width: 768px) {
            #sidebar {
                margin-left: -230px;
            }
            #sidebar.active {
                margin-left: 0;
            }
            #sidebarCollapse span {
                display: none;
            }
        }

        /* -----------------------------------
                    FOOOTER
        ------------------------------------ */

        .naslovi {
            margin-bottom: -1%;
            color: #FC766A;
        }
        footer {
            background-color: #9ED9CC;
        }

        .selected{
            color: #008C76;
            background: #ddd;
        }
    </style>
</head>
<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3 id="naslov">Bookhive</h3>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="/user">Home</a>
                </li>
                @if (User.IsInRole("StandardUser"))
                {
                    <li>
                        <a asp-controller="UserBooks" asp-action="Index">My Books</a>
                    </li>
                }
                @if (User.IsInRole("StandardUser"))
                {
                    <li>
                        <a asp-controller="User" asp-action="GetMyBookClubs">My Book Clubs</a>
                    </li>
                }
                @if (User.IsInRole("StandardUser"))
                {
                    <li>
                        <a asp-controller="User" asp-action="GetMyWishList">My Wishlist</a>
                    </li>
                }
                @if (User.IsInRole("StandardUser"))
                {
                    <li>
                        <a asp-controller="Order" asp-action="Index">My Orders</a>
                    </li>
                }
                @if (User.IsInRole("Administrator"))
                {
                    <li>
                        <a asp-controller="Order" asp-action="Index">All Orders</a>
                    </li>
                }
                <li>
                    <a asp-controller="Authors" asp-action="Index">Authors</a>
                </li>
                <li>
                    <a asp-controller="Books" asp-action="Index">Books</a>
                </li>
                @if (User.IsInRole("StandardUser"))
                {
                    <li>
                        <a asp-controller="BookClub" asp-action="Index">Book Clubs</a>
                    </li>
                }
                @if (User.IsInRole("StandardUser") || User.IsInRole("Administrator"))
                {
                    <li>
                        <a asp-controller="Invitation" asp-action="GetMyInvitations" class="position-relative">
                            Invitations
                        </a>
                    </li>
                }
                <li>
                    <a href="/bookshops">Bookshops</a>
                </li>

                @if (User.IsInRole("Administrator"))
                {
                    <li>
                        <a href="https://localhost:44321/User/ImportUsers">Import Users</a>
                    </li>
                }
            </ul>
            @if (User.IsInRole("StandardUser") || User.IsInRole("Administrator"))
            {
                <div id="logout" style="position: fixed;">
                    <a href="/account/logout">Logout</a>
                </div>
            }
            </nav>

        <!-- Page Content  -->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" id="topbar">
                <div class="container-fluid ">
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span></span>
                    </button>
                    @if (User.IsInRole("Administrator") || User.IsInRole("StandardUser"))
                    {
                        <div sec:authorize="hasAnyRole('ROLE_ADMIN','ROLE_USER')" id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">
                                <li class="nav-item active">
                                    @*<a class="nav-link" href="/account/profile" id="myProfile">My profile</a>*@
                                    @if (User.IsInRole("StandardUser"))
                                    {
                                        <a style="padding: 0; display: inline-block" class="nav-link" href="/shoppingcart" id="myProfile"><img height="65" src="/shopping_cart.png" /></a>

                                    }
                                    <a style="padding: 0; margin-left: 15px; display: inline-block" class="nav-link" href="/account/profile" id="myProfile"><img height="55" src="/profile_icon.png" /></a>
                                </li>
                            </ul>
                        </div>
                    }
                    </div>
            </nav>
            <div class="container">
                <main role="main" class="pb-3">
                    <!-- Body Content -->
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    @*    <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - BookHiveDB.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)*@
    <!--<div class="container">
        <main role="main" class="pb-3">-->
    <!-- Body Content -->
    <!--@RenderBody()
        </main>
    </div>-->

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>
</html>